### ISSUE TITLE
not incrementing selection

### ISSUE THREAD

**Issue by dlieu** [yulanggong/IncrementSelection#10]
sublime: ver 3.2.2; build 3211
os: ubuntu 18.04.3

Not incrementing numbers as expected
EG. I select 1,2 and 3; run command and getting back 1,2,3
`[1] text [2] text [3] text  ->  1| text 2| text 3| text
`
Desired result is increment to numbers 2,3,4:
`[1] text [2] text [3] text  ->  2| text 3| text 4| text`

**Comment by yulanggong** [comment]
Yes this plugin dose not work in the way you expected. 

Here is a solution by using this plugin:

Select all selections.
```
[1] text [2] text [3] text
```
Type `2` as a start number and select it.
```
[2] text [2] text [2] text
```
Run the command and the result is:
```
2| text 3| text 4| text
```
