### ISSUE TITLE
Shortcut doesn't work on Mac

### ISSUE THREAD

**Issue by theonestep4** [yulanggong/IncrementSelection#3]
When I try to use this package on my Mac (pressing the shortcut command + ctrl + i) I get the character `1` instead of executing the package.

**Comment by alexcroox** [comment]
Same, can't find any settings to change the binding either...

**Comment by Razer6** [comment]
:+1: Same here on OSX

**Comment by indrayam** [comment]
This is an amazingly simple, but useful plugin. Well done!!!
